<?php
    $this->headTitle('Meetup Group Administration');
?>

<a class="pull-right btn btn-warning" href="<?= $this->url('admin/meetup-group/event-refresh-all', ['id' => $this->meetupGroup->getId()]); ?>">
    Refresh Event List
</a>

<h1>Administration</h1>
<h2><?= $this->escapeHtml($this->meetupGroup->getName()); ?></h2>

Station members: <?= sizeof($this->meetupGroup->getProfile()); ?>
of <?= $apiMeetupGroup['members']; ?> Meetup members



<?php
#print_r($apiMeetupGroup);
