<?php
    $this->headTitle('Meetup Group Administration');
?>

<a class="pull-right btn btn-warning" href="<?= $this->url('admin/meetup-group/event-refresh-all', ['id' => $this->meetupGroup->getId()]); ?>">
    Refresh Event List
</a>

<h1>Administration</h1>
<h2><?= $this->escapeHtml($this->meetupGroup->getName()); ?></h2>

Station members: <?= sizeof($this->meetupGroup->getProfile()); ?>
of <?= $apiMeetupGroup['members']; ?> Meetup members

<table class="table table-striped table-hover">
    <caption>Events</caption>
    <thead>
        <tr>
            <th>Logo</th>
            <th>Venue</th>
            <th>Date</th>
            <th>Name</th>
            <th>RSVP</th>
        </tr>
    </thead>

    <tbody>
    <?php
    foreach ($this->meetupGroup->getEvent() as $event) {
    ?>
        <tr>
            <td>
                <?php
                if ($event->getVenue() and $event->getVenue()->getSponsor() and $event->getVenue()->getSponsor()->getLogoUrl()) {
                ?>
                    <img src="<?= $event->getVenue()->getSponsor()->getLogoUrl(); ?>" width="40">
                <?php
                }
                ?>
            </td>
            <td>
                <?php
                if ($event->getVenue()) {
                ?>
                <a class="btn btn-info" href="<?= $this->url('admin/venue/detail', ['id' => $event->getVenue()->getId()]); ?>">
                    <?= $this->escapeHtml($event->getVenue()->getName()); ?>
                </a>
                <?php
                }
                ?>
            </td>
            <td>
                <a class="btn btn-info" href="<?= $this->url('admin/event', ['id' => $event->getId()]); ?>">
                    <?= $event->getScheduledAtWithOffset()->format('Y-m-d H:i:s'); ?>
                </a>
            </td>
            <td><?= $this->escapeHtml($event->getName()); ?></td>
            <td><?= $this->escapeHtml($event->getYesRsvpCount()); ?></td>
        </tr>
    <?php
    }
    ?>
    </tbody>
</table>

