<?php
    $this->headTitle('Sponsor Contribution');
?>

<div class="btn-group pull-right">
    <a class="btn btn-success" href="<?= $this->url('admin/meetup-group/sponsor-contribution/create', ['id' => $this->meetupGroup->getId()]); ?>">
        Create Sponsor Contribution
    </a>
</div>

<h1><?= $this->escapeHtml($this->meetupGroup->getName()); ?></h1>

<?= $this->partial('admin/partial/sponsor-contribution-table', ['sponsorContributions' => $this->meetupGroup->getSponsorContribution()]); ?>

