<?php
$this->headTitle('Create Venue Question');
?>

<h1>
    Create Venue Question
</h1>

<?php
$form = $this->form;

$form->add(array(
    'type' => 'Button',
    'name' => 'submit',
    'attributes' => array(
        'type'  => 'submit',
        'class' => 'btn btn-warning',
        'value' => 'Edit',
    )
));

$form->setAttribute('action', $this->url('admin/venue-question/edit', ['id' => $this->venueQuestion->getId()]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-container container">
    <div class="col-md-12">
        <?php
        echo $this->formLabel($form->get('body'));
        echo $this->formText($form->get('body'));
        echo $this->formElementErrors()
            ->setMessageOpenFormat('<div class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><ul><li>')
            ->setMessageSeparatorString('</li><li>')
            ->setMessageCloseString('</li></ul></div>')
            ->render($form->get('body'));
        ?>
    </div>
</div>
<br>
<div class="form-container container">
    <div class="col-md-12">
        <?= $this->formSubmit($form->get('submit')); ?>
        <?= $this->formHidden($form->get('csrf')); ?>
    </div>
</div>

<?= $this->form()->closeTag(); ?>