<?php
    $this->headTitle('Meetup Group Event');
?>
<div class="btn-group pull-right">
    <a class="btn btn-success" href="<?= $this->url('admin/meetup-group/sponsor-contribution/create', ['id' => $this->event->getMeetupGroup()->getId(), 'event_id' => $this->event->getId()]); ?>">
        Create Sponsor Contribution
    </a>
</div>

<h1>Meetup Group Event</h1>
<h2> Meetup Group:
    <a class="btn btn-info" href="<?= $this->url('admin/meetup-group', ['id' => $this->event->getMeetupGroup()->getId()]); ?>">
        <?= $this->escapeHtml($this->event->getMeetupGroup()->getName()); ?>
    </a>
</h2>

<h3><?= $this->event->getScheduledAtWithOffset()->format('Y-m-d H:i:s'); ?> <?= $this->escapeHtml($this->event->getName()); ?></h3>

<table class="table table-striped table-hover">
    <caption>Event Details</caption>
    <thead>
    </thead>
    <tbody>
        <tr>
            <th>Meetup Group</th>
            <td>
                <a class="btn btn-info" href="<?= $this->url('admin/meetup-group', ['id' => $this->event->getMeetupGroup()->getId()]); ?>">
                    <?= $this->escapeHtml($this->event->getMeetupGroup()->getName()); ?>
                </a>
            </td>
        </tr>
        <tr>
            <th>Event Name</th>
            <td>
                <a href="<?= $this->event->getUrl(); ?>">
                    <?= $this->escapeHtml($this->event->getName()); ?>
                </a>
            </td>
        </tr>
        <tr>
            <th>Scheduled At</th>
            <td>
                <a class="btn btn-info" href="<?= $this->url('admin/event/detail', ['id' => $this->event->getId()]); ?>">
                    <?= $this->event->getScheduledAtWithOffset()->format('Y-m-d H:i:s'); ?>
                </a>
            </td>
        </tr>
        <tr>
            <th>Created At</th>
            <td><?= $this->event->getCreatedAtWithOffset()->format('Y-m-d H:i:s'); ?></td>
        </tr>
        <tr>
            <th>Updated At</th>
            <td>
                <?= $this->event->getUpdatedAtWithOffset()->format('Y-m-d H:i:s'); ?>
            </td>
        </tr>
        <tr>
            <th>Description</th>
            <td><?= $this->markdown($this->event->getDescription()); ?></td>
        </tr>
        <tr>
            <th>Status</th>
            <td><?= $this->escapeHtml($this->event->getStatus()); ?></td>
        </tr>
        <tr>
            <th>Visibility</th>
            <td><?= $this->escapeHtml($this->event->getVisibility()); ?></td>
        </tr>
        <tr>
            <th>RSVP Limit</th>
            <td><?= $this->event->getRsvpLimit(); ?></td>
        </tr>
        <tr>
            <th>Yes RSVP Count</th>
            <td><?= $this->event->getYesRsvpCount(); ?></td>
        </tr>
        <tr>
            <th>Maybe RSVP Count</th>
            <td><?= $this->event->getMaybeRsvpCount(); ?></td>
        </tr>
        <tr>
            <th>Waitlist Count</th>
            <td><?= $this->event->getWaitlistCount(); ?></td>
        </tr>
        <tr>
            <th>Headcount</th>
            <td><?= $this->event->getHeadcount(); ?></td>
        </tr>
    </tbody>
</table>










</table>

<?= $this->partial('admin/partial/sponsor-contribution-table', ['sponsorContributions' => $this->event->getSponsorContribution()]); ?>
