<a class="btn btn-warning pull-right" href="<?= $this->url('admin/sponsor/edit', ['id' => $this->sponsor->getId()]); ?>">
    Edit Sponsor
</a>

<h1>Sponsor</h1>

<?php
if ($this->sponsor->getLogoUrl()) {
?>
<img title="<?= $this->escapeHtml($this->sponsor->getName()); ?> src="<?= $this->sponsor->getLogoUrl(); ?>">
<?php
}
?>

<h2><?= $this->escapeHtml($this->sponsor->getName()); ?></h2>

<?php
if (sizeof($this->sponsor->getVenue())) {
?>
<table class="table table-striped table-hover">
    <caption>Venues</caption>
    <thead>
        <tr>
            <th>Name</th>
            <th>Address</th>
            <th>Contact</th>
        </tr>
    </thead>

    <tbody>
    <?php
    foreach ($this->sponsor->getVenue() as $venue) {
    ?>
        <tr>
            <td><?= $this->escapeHtml($venue->getName()); ?></td>
            <td><?= nl2br($this->escapeHtml($this->venue->getCompleteAddress())); ?></td>
            <td><?= $this->escapeHtml($venue->getContact()); ?></td>
        </tr>
    <?php
    }
    ?>
    </tbody>
</table>
<?php
}
?>