<?php
$this->headTitle('Edit Sponsor');
?>

<h1>
    Edit Sponsor
</h1>

<?php
$form = $this->form;

$form->add(array(
    'type' => 'Button',
    'name' => 'submit',
    'options' => array(
        'label'   => 'Create',
    ),
    'attributes' => array(
        'type'  => 'submit',
        'class' => 'btn btn-warning',
        'value' => 'Edit',
    )
));


$form->setAttribute('action', $this->url('admin/sponsor/edit', ['id' => $this->sponsor->getId()]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-container container">
    <div class="col-md-12">
        <?php
        echo $this->formLabel($form->get('name'));
        echo $this->formText($form->get('name'));
        echo $this->formElementErrors()
            ->setMessageOpenFormat('<div class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><ul><li>')
            ->setMessageSeparatorString('</li><li>')
            ->setMessageCloseString('</li></ul></div>')
            ->render($form->get('name'));
        ?>
    </div>

    <div class="col-md-12">
        <?php
        echo $this->formLabel($form->get('url'));
        echo $this->formUrl($form->get('url'));
        echo $this->formElementErrors()
            ->setMessageOpenFormat('<div class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><ul><li>')
            ->setMessageSeparatorString('</li><li>')
            ->setMessageCloseString('</li></ul></div>')
            ->render($form->get('url'));
        ?>
    </div>

    <div class="col-md-12">
        <?php
        echo $this->formLabel($form->get('logoUrl'));
        echo $this->formUrl($form->get('logoUrl'));
        echo $this->formElementErrors()
            ->setMessageOpenFormat('<div class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><ul><li>')
            ->setMessageSeparatorString('</li><li>')
            ->setMessageCloseString('</li></ul></div>')
            ->render($form->get('logoUrl'));
        ?>
    </div>

    <div class="col-md-12">
    <?php
    echo $this->formMarkdown($form->get('description'));
    echo $this->formElementErrors()
        ->setMessageOpenFormat('<div class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><ul><li>')
        ->setMessageSeparatorString('</li><li>')
        ->setMessageCloseString('</li></ul></div>')
        ->render($form->get('description'));
    ?>
    </div>

</div>
<br>
<div class="form-container container">
    <div class="col-md-12">
        <?= $this->formSubmit($form->get('submit')); ?>
        <a class="confirm" href="<?= $this->url('admin/sponsor/detail', ['id' => $this->sponsor->getId()]); ?>">
            cancel
        </a>
        <?= $this->formHidden($form->get('csrf')); ?>
    </div>
</div>

<?= $this->form()->closeTag(); ?>