<a class="btn btn-success pull-right" href="<?= $this->url('admin/sponsor/create'); ?>">
    Create Sponsor
</a>

<h1>Sponsors</h1>

<table class="table table-striped table-hover">
    <caption>Sponsors</caption>
    <thead>
        <tr>
            <th>Logo</th>
            <th>Name</th>
            <th>URL</th>
            <th>Description</th>
        </tr>
    </thead>

    <tbody>
    <?php
    foreach ($sponsors as $sponsor) {
    ?>
        <tr>
            <td><?php
                if ($sponsor->getLogoUrl()) {
                ?>
                    <img src="<?= $sponsor->getLogoUrl(); ?>" width="40">
                <?php
                }
                ?>
            </td>
            <td>
                <a class="btn btn-info" href="<?= $this->url('admin/sponsor/detail', ['id' => $sponsor->getId()]); ?>">
                    <?= $this->escapeHtml($sponsor->getName()); ?>
                </a>
            </td>
            <td>
                <a href="<?= $sponsor->getUrl(); ?>">
                    <?= $this->escapeHtml($sponsor->getUrl()); ?>
                </a>
            </td>
            <td><?= $this->escapeHtml($sponsor->getDescription()); ?></td>
        </tr>
    <?php
    }
    ?>
    </tbody>
</table>
