<a class="btn btn-success pull-right" href="<?= $this->url('admin/sponsor-create'); ?>">
    Create Sponsor
</a>

<h1>Sponsors</h1>

<table class="table table-striped table-hover">
    <caption>Sponsors</caption>
    <thead>
        <tr>
            <th>Logo</th>
            <th>Name</th>
            <th>URL</th>
            <th>Description</th>
        </tr>
    </thead>

    <tbody>
    <?php
    foreach ($sponsors as $sponsor) {
    ?>
        <tr>
            <td><img src="<?= $sponsor->getLogoUrl(); ?> width="40"></td>
            <td><?= $this->escapeHtml($sponsor->getName()); ?></td>
            <td>
                <a href="<?= $sponsor->getUrl(); ?>">
                    <?= $this->escapeHtml($sponsor->getUrl()); ?>
                </a>
            </td>
            <td><?= $this->escapeHtml($sponsor->getDescription()); ?></td>
        </tr>
    <?php
    }
    ?>
    </tbody>
</table>
