<?php
$this->headTitle('Edit Venue');
?>

<h1>
    Edit Venue
</h1>

<h2><?= $this->escapeHtml($this->venue->getName()); ?></h2>

<?php
$form = $this->form;

$form->add(array(
    'type' => 'Button',
    'name' => 'submit',
    'options' => array(
        'label'   => 'Edit',
    ),
    'attributes' => array(
        'type'  => 'submit',
        'class' => 'btn btn-warning',
        'value' => 'Edit',
    )
));


$form->setAttribute('action', $this->url('admin/venue/edit', ['id' => $this->venue->getId()]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-container container">
    <div class="col-md-12">
        <?php
        // Add none selector for sponsor
        $form->get('sponsor')->setValueOptions(['' => 'none'] + $form->get('sponsor')->getValueOptions());

        echo $this->formLabel($form->get('sponsor'));
        echo $this->formSelect($form->get('sponsor'));
        echo $this->formElementErrors()
            ->setMessageOpenFormat('<div class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><ul><li>')
            ->setMessageSeparatorString('</li><li>')
            ->setMessageCloseString('</li></ul></div>')
            ->render($form->get('sponsor'));
        ?>
    </div>

    <div class="col-md-12">
        <?php
        echo $this->formLabel($form->get('capacity'));
        echo $this->formNumber($form->get('capacity'));
        echo $this->formElementErrors()
            ->setMessageOpenFormat('<div class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><ul><li>')
            ->setMessageSeparatorString('</li><li>')
            ->setMessageCloseString('</li></ul></div>')
            ->render($form->get('capacity'));
        ?>
    </div>

    <div class="col-md-12">
    <?php
    echo $this->formMarkdown($form->get('description'));
    echo $this->formElementErrors()
        ->setMessageOpenFormat('<div class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><ul><li>')
        ->setMessageSeparatorString('</li><li>')
        ->setMessageCloseString('</li></ul></div>')
        ->render($form->get('description'));
    ?>
    </div>

    <div class="col-md-12">
    <?php
    echo $this->formMarkdown($form->get('contact'));
    echo $this->formElementErrors()
        ->setMessageOpenFormat('<div class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><ul><li>')
        ->setMessageSeparatorString('</li><li>')
        ->setMessageCloseString('</li></ul></div>')
        ->render($form->get('contact'));
    ?>
    </div>

    <div class="col-md-12">
    <?php
    echo $this->formMarkdown($form->get('security'));
    echo $this->formElementErrors()
        ->setMessageOpenFormat('<div class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><ul><li>')
        ->setMessageSeparatorString('</li><li>')
        ->setMessageCloseString('</li></ul></div>')
        ->render($form->get('security'));
    ?>
    </div>

    <div class="col-md-12">
    <?php
    echo $this->formMarkdown($form->get('equipment'));
    echo $this->formElementErrors()
        ->setMessageOpenFormat('<div class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><ul><li>')
        ->setMessageSeparatorString('</li><li>')
        ->setMessageCloseString('</li></ul></div>')
        ->render($form->get('equipment'));
    ?>
    </div>

</div>
<br>
<div class="form-container container">
    <div class="col-md-12">
        <?= $this->formSubmit($form->get('submit')); ?>
        <?= $this->formHidden($form->get('csrf')); ?>
    </div>
</div>

<?= $this->form()->closeTag(); ?>