<?php
if ($this->isAllowed('administration', 'access')) {
?>
    <a class="btn btn-warning pull-right" href="https://www.meetup.com">Edit at meetup.com</a>
<?php
}
?>


<h1>Venue</h1>
<h2><?= $this->escapeHtml($this->venue->getName()); ?></h2>

<div class="container">
    <table class="table">
        <tbody>
            <tr>
                <th>Address</th>
                <td>
                    <?php
                    if ($this->venue->getAddress1()) {
                        echo $this->escapeHtml($this->venue->getAddress1());
                        echo '<br>';
                    }

                    if ($this->venue->getAddress2()) {
                        echo $this->escapeHtml($this->venue->getAddress2());
                        echo '<br>';
                    }

                    if ($this->venue->getAddress3()) {
                        echo $this->escapeHtml($this->venue->getAddress3());
                        echo '<br>';
                    }

                    if ($this->venue->getCity()) {
                        echo $this->escapeHtml($this->venue->getCity());
                        echo ', ';
                    }

                    if ($this->venue->getState()) {
                        echo $this->escapeHtml($this->venue->getState());
                    }

                    if ($this->venue->getZip()) {
                        echo ' ' . $this->escapeHtml($this->venue->getZip());
                    }

                    if ($this->venue->getCountry()) {
                        echo '<br>';
                        echo $this->escapeHtml($this->venue->getCountry());
                    }
                    ?>

                </td>
            </tr>
            <?php
            if ($this->venue->getPhone()) {
            ?>
            <tr>
                <th>Phone</th>
                <td><?= $this->escapeHtml($this->venue->getPhone()); ?></td>
            </tr>
            <?php
            }

            if ($this->venue->getCapacity()) {
            ?>
            <tr>
                <th>Capacity</th>
                <td><?= (int) $this->venue->getCapacity(); ?></td>
            </tr>
            <?php
            }

            if ($this->venue->getContact()) {
            ?>
            <tr>
                <th>Contact</th>
                <td><?= $this->escapeHtml($this->venue->getContact()); ?></td>
            </tr>
            <?php
            }

            if ($this->venue->getLatitude()) {
            ?>
            <tr>
                <th>Latitude</th>
                <td><?= $this->escapeHtml($this->venue->getLatitude()); ?></td>
            </tr>
            <?php
            }

            if ($this->venue->getLongitude()) {
            ?>
            <tr>
                <th>Longitude</th>
                <td><?= $this->escapeHtml($this->venue->getLongitude()); ?></td>
            </tr>
            <?php
            }
            ?>
        </tbody>
    </table>
</div>

<?php
if ($this->venue->getDescription()) {
?>
<div class="container">
    <h3>Description</h3>
    <?= $this->escapeHtml($this->venue->getDescription()); ?>
</div>
<?php
}
?>

<?php
if ($this->venue->getSecurity()) {
?>
<div class="container">
    <h3>Security</h3>
    <?= $this->escapeHtml($this->venue->getSecurity()); ?>
</div>
<?php
}
?>

<?php
if ($this->venue->getEquipment()) {
?>
<div class="container">
    <h3>Equipment</h3>
    <?= $this->escapeHtml($this->venue->getEquipment()); ?>
</div>
<?php
}


if ($this->venue->getEvent()) {
?>
<table class="table table-striped table-hover">
    <caption>Events</caption>
    <thead>
        <tr>
            <th>Meetup Group</th>
            <th>Scheduled At</th>
            <th>Event</th>
        </tr>
    </thead>
    <tbody>
    <?php
    foreach ($this->venue->getEvent() as $event) {
    ?>
        <tr>
            <td><?= $this->escapeHtml($event->getMeetupGroup()->getName()); ?></td>
            <td><?= $event->getScheduledAt()->format('Y-m-d H:i:s'); ?></td>
            <td>
                <a class="btn btn-info" href="<?= $this->url('admin/event', ['id' => $event->getId()]); ?>">
                    <?= $this->escapeHtml($event->getName()); ?>
                </a>
            </td>
        </tr>
    <?php
    }
    ?>
    </tbody>
</table>
<?php
}