<div class="btn-group pull-right">
    <a class="btn btn-info" href="<?= $this->url('admin/venue/detail', ['id' => $this->venue->getId()]); ?>">
        Return To Venue
    </a>
</div>


<h1>Venue Questions</h1>
<h2><?= $this->escapeHtml($this->venue->getName()); ?></h2>
<?php
if ($this->venue->getSponsor()) {
?>
    <a class="btn btn-info" href="<?= $this->url('admin/sponsor/detail', ['id' => $this->venue->getSponsor()->getId()]); ?>">
        <?= $this->escapeHtml($this->venue->getSponsor()->getName()); ?>
    </a>
<?php
}
?>

<div class="container">
    <table class="table table-striped table-hover">
        <caption>Venue Questions
            <a class="btn btn-success" href="<?= $this->url('admin/venue-question/create', ['venue_id' => $this->venue->getId()]); ?>">
                Create Venue Question
            </a>
        </caption>
        <thead>
            <tr>
                <th>Question</th>
                <th>Actions</th>
            <tr>
        </thead>

        <tbody>
            <?php
            foreach ($this->venue->getVenueQuestion() as $venueQuestion) {
            ?>
                <tr>
                    <td><?= $this->escapeHtml($venueQuestion->getBody()); ?></td>
                    <td class="text-right">
                        <div class="btn-group">
                            <a class="btn btn-warning" href="<?= $this->url('admin/venue-question/edit', ['id' => $venueQuestion->getId()); ?>">
                                Edit
                            </a>
                            <a class="btn btn-danger" href="<?= $this->url('admin/venue-question/delete', ['id' => $venueQuestion->getId()); ?>">
                                Delete
                            </a>
                        </div>
                    </td>
                </tr>
            <?php
            }
            ?>
        </tbody>
    </table>
</div>