<?php
$this->headTitle('Edit Sponsor Contribution');
?>

<h1>
    Edit Sponsor Contribution
</h1>

<h2><?= $this->escapeHtml($this->sponsorContribution->getMeetupGroup()->getName()); ?></h2>

<?php
$form = $this->form;

$form->add(array(
    'type' => 'Button',
    'name' => 'submit',
    'attributes' => array(
        'type'  => 'submit',
        'class' => 'btn btn-warning',
        'value' => 'Edit',
    )
));

$form->setAttribute('action', $this->url('admin/sponsor-contribution/edit', ['id' => $this->sponsorContribution->getId()]));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-container container">
    <div class="col-md-12">
        <?php
        echo $this->formLabel($form->get('sponsor'));
        echo $this->formSelect($form->get('sponsor'));
        echo $this->formElementErrors()
            ->setMessageOpenFormat('<div class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><ul><li>')
            ->setMessageSeparatorString('</li><li>')
            ->setMessageCloseString('</li></ul></div>')
            ->render($form->get('sponsor'));
        ?>
    </div>

    <div class="col-md-12">
        <?php
        // Add none selector for sponsor
        $form->get('event')->setValueOptions(['' => 'none'] + $form->get('event')->getValueOptions());

        echo $this->formLabel($form->get('event'));
        echo $this->formSelect($form->get('event'));
        echo $this->formElementErrors()
            ->setMessageOpenFormat('<div class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><ul><li>')
            ->setMessageSeparatorString('</li><li>')
            ->setMessageCloseString('</li></ul></div>')
            ->render($form->get('event'));
        ?>
    </div>

    <div class="col-md-12">
        <?php
        echo $this->formLabel($form->get('title'));
        echo $this->formText($form->get('title'));
        echo $this->formElementErrors()
            ->setMessageOpenFormat('<div class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><ul><li>')
            ->setMessageSeparatorString('</li><li>')
            ->setMessageCloseString('</li></ul></div>')
            ->render($form->get('title'));
        ?>
    </div>

    <div class="col-md-12">
    <?php
    echo $this->formMarkdown($form->get('description'));
    echo $this->formElementErrors()
        ->setMessageOpenFormat('<div class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><ul><li>')
        ->setMessageSeparatorString('</li><li>')
        ->setMessageCloseString('</li></ul></div>')
        ->render($form->get('description'));
    ?>
    </div>

    <div class="col-md-12">
    <?php
    echo $this->formMarkdown($form->get('receivedWhat'));
    echo $this->formElementErrors()
        ->setMessageOpenFormat('<div class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><ul><li>')
        ->setMessageSeparatorString('</li><li>')
        ->setMessageCloseString('</li></ul></div>')
        ->render($form->get('receivedWhat'));
    ?>
    </div>

    <div class="col-md-12">
    <?php
    echo $this->formMarkdown($form->get('receivedWhy'));
    echo $this->formElementErrors()
        ->setMessageOpenFormat('<div class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><ul><li>')
        ->setMessageSeparatorString('</li><li>')
        ->setMessageCloseString('</li></ul></div>')
        ->render($form->get('receivedWhy'));
    ?>
    </div>

    <div class="col-md-12">
    <?php
    echo $this->formMarkdown($form->get('receivedHow'));
    echo $this->formElementErrors()
        ->setMessageOpenFormat('<div class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><ul><li>')
        ->setMessageSeparatorString('</li><li>')
        ->setMessageCloseString('</li></ul></div>')
        ->render($form->get('receivedHow'));
    ?>
    </div>

</div>
<br>
<div class="form-container container">
    <div class="col-md-12">
        <?= $this->formSubmit($form->get('submit')); ?>
        <?= $this->formHidden($form->get('csrf')); ?>
    </div>
</div>

<?= $this->form()->closeTag(); ?>